#logging:
#  pattern:
##    console: "%d - %msg%n"
##  path: D:\JavaInstall\selllog\
#  file: D:\JavaInstall\selllog\log1.log
#  level:
#    com.imooc.LoggerTest: debugspring:spring:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell